export const LOADING_POSTAL_CODE = 'core/LOADING_STOP'
export const ADDRESS_LOAD = 'core/ADDRESS_LOAD'
export const SHOW_MODAL_ERROR = 'core/SHOW_MODAL_ERROR'
export const MESSAGE_ERROR_MODAL = 'core/MESSAGE_ERROR_MODAL'
export const POKEDEX_LIST = 'core/POKEDEX_LIST'
